r-anime/stylesheet

- style.css
definitely not farming PR's for hacktoberfest or anything
> change urban's flair

- style.css
This fixes the problem of minimization when the value of `background` is `0 0`
> Fix the offset for some comment faces at the top of the spirtesheets

- .travis.yml
- .update/updateSubreddit.py
- style.css
still definitely not PR farming or anything
> Remove #evilbot comment face

- style.css
> Removed red spoiler text

- style.css
Merging spritesheet1 through 4 into "Old Sheet 1" (https://i.imgur.com/6TNAio7.png) and changing spritesheet5 into "OldSheet2" (https://i.imgur.com/P33TVeT.png) so we can free up image slots.
Geo I've never used CSS in my life before, please be gentle senpai
> Merging spritesheets 1-5

- style.css
I am a mod why can't I do this stuff right
> Merge Kukuku

- style.css
"redditors who stayed home and watched anime for halloween"
"redditors who ate lots of candy anyway"
Don't okay it until after halloween
Find something more permanent later
> subscriber count change

- style.css
> Updated Sub Count Description

- style.css
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
> changed flair, removed faux flair

- style.css
Is this how pull requests work? I always get confused.
> default (?) sub counter

- style.css
merging please make this one work
> merge AMA flair

- style.css
geo this is like important code and I don't know what I'm doing pls check that I'm doing the right thing k thx bye
> fanart thumbnail

- style.css
https://mod.reddit.com/mail/all/3lj5v
> Timeline -> world line

- style.css
this will probably not work at all considering the sass branch, but who knows
> add one comment face

- style.css
> Hi people following this repo for some reason

- style.css
> readd #dancewithit commentface

- style.css
i dont like sending useless notifications like this in sub mod chat pls
> why doesn't github let me merge branches without a pull request

- style.css
> OldSheets Merge into 1 sheet

- style.css
> Adding Discord button to the sub sidebar

- style.css
Geo is too ~~lazy~~ busy to do this right at the moment so I figured I'd give it a shot.
> add recommendation to filter

- .gitignore
- _flairs.scss
Remove flair for users that haven't been active on /r/anime for at least one year (excluding former mods).
> Remove inactive user flair

- src/_commentfaces.scss
> forgot a hash

- src/_commentfaces.scss
The one with the most syntax errors wins. That's what css is!
> parentheses to square bracket

- src/_everything.scss
we have filters, lets use them for people who hate memes (for whatever reason)
If you add this don't forget to change the sidebar dropdown too.
> add meme filter

- src/_everything.scss
I don't have edit rights but, yknow gotta save space in the stylesheet where you can.
> "rollback" meme filter

- .travis.yml
- utils/config_default.yml
- utils/validate.py
The script validates the CSS and Local Images. The existing images in the subreddit are ignored.
> Add a validation script for pull requests

- src/_everything.scss
> Undo reddit's stupid changes to the "message the mods" button

- .github/workflows/build-and-deploy.yml
- src/_everything.scss
- src/_infobar.scss
- src/util/_SassySort.scss
- src/util/_functions.scss
See https://sass-lang.com/documentation/breaking-changes/slash-div
> Use math.div instead of slash for division

- _flairs.scss
- main.scss
Updates the info comment at the top of the file to link to my current Reddit account. Also removes CSS flairs from my old account.
> Update maintainer Reddit name

- src/_linkflair.scss
- src/_userflair.scss
Sets post flair min width to even out smaller sizes and changes user flair emoji size to 24px.
> Flair size updates

- src/_sidebar.scss
- src/_sidebarimages.scss
Reworks the sidebar images to work based on a config variable that holds information about all the images being displayed. Format for configuring it is documented. This should hopefully make it much easier for y'all to add/remove sidebar images as you like.
> Support an arbitrary number of sidebar images

- .github/workflows/build-and-deploy.yml
- build/backend/RedditBackend.ts
- build/index.ts
> add secret css via env variable
